/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#131b2e",
        "on-primary": "#1d00a5",
        outline: "#918fa1",
        "tertiary-fixed-dim": "#ffb95f",
        "outline-variant": "#464555",
        "secondary-container": "#00a572",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-primary-container": "#dad7ff",
        "on-surface": "#dae2fd",
        "tertiary-container": "#885500",
        "on-primary-fixed-variant": "#3323cc",
        error: "#ffb4ab",
        "on-secondary": "#003824",
        "secondary-fixed": "#6ffbbe",
        "surface-bright": "#31394d",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#4edea3",
        "surface-container": "#171f33",
        "inverse-primary": "#4d44e3",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#e2dfff",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060e20",
        "error-container": "#93000a",
        "surface-variant": "#2d3449",
        "surface-tint": "#c3c0ff",
        "surface-container-high": "#222a3d",
        "primary-fixed-dim": "#c3c0ff",
        surface: "#0b1326",
        "inverse-surface": "#dae2fd",
        tertiary: "#ffb95f",
        "on-primary-fixed": "#0f0069",
        primary: "#c3c0ff",
        "on-background": "#dae2fd",
        secondary: "#4edea3",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed-variant": "#005236",
        "primary-container": "#4f46e5",
        "inverse-on-surface": "#283044",
        "on-tertiary": "#472a00",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-container": "#00311f",
        "on-surface-variant": "#c7c4d8",
        background: "#0b1326",
        "on-tertiary-container": "#ffd4a4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xl: "64px",
        lg: "40px",
        xs: "8px",
        gutter: "24px",
        "margin-desktop": "48px",
        sm: "16px",
        "margin-mobile": "16px",
        md: "24px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "scan": "scan 3s linear infinite",
        "float": "float 6s ease-in-out infinite",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        scan: {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 10px rgba(78,222,163,0.3)" },
          "50%": { boxShadow: "0 0 25px rgba(78,222,163,0.6)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "grid-pattern": "radial-gradient(rgba(195, 192, 255, 0.1) 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
};
